version: "3.7"
networks:
  request-count:
services:
  redis-server:
    image: "redis"
    deploy:
      replicas: 1
    networks:
      - request-count

  go-server:
    build: ./
    expose:
      - "8080"
    deploy:
      replicas: 3
    depends_on:
      - redis-server
    volumes:
      - ./:/app
    networks:
      - request-count
    environment:
      PORT: 8080

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-server
    ports:
      - "4000:4000"
    networks:
      - request-count
